shibatch/sleef

src/arch/helperadvsimd.h
src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx512f.h
src/arch/helperneon32.h
src/arch/helperpurec.h
src/arch/helpersse2.h
src/arch/helpervecext.h

The `vcastf_f_vf` routine is needed only when debugging with
MSVC. This patch enables the function when compiling with MSVC, for
those architectures that MSVC supports.

[cleanup] Guard MSVC specific functions.

---

src/libm/sleefdp.c
src/libm/sleefsimddp.c

ddadd and ddadd2 are functions for double-double addition.
ddadd is simpler and faster than ddadd2, but it requires the first argument to be larger the the second argument.
Through my testing, this condition only holds for the 1st, 5th, 6th and 7th addition in argument reduction.
In the previous source code, all additions are carried out by ddadd, which is potentially dangerous.

This patch fixes potential problems in ulp 1 versions of trig functions.

---

src/arch/helperavx2_128.h
src/libm-tester/Makefile
src/libm-tester/Makefile.vc
src/libm-tester/iutsimd.c
src/libm-tester/tester2simddp.c
src/libm-tester/tester2simdsp.c
src/libm/Makefile
src/libm/Makefile.vc
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

It also separates functions that only utilize SSE2 and those utilize SSE4.

This patch adds new helper avx2_128.

---

src/libm-tester/tester.c

This patch forces the fflushing of `stdin` and `stdout` in `tester.c` to prevent CPU feature detection failures.

Flush stdin / stdout in the tester.

---

.travis.yml

There will be subsequent commits. I do not know what else this changes requires yet as there is no way of triggering Travis before hand.

Add clang testing in the CI.

---

src/libm-tester/CMakeLists.txt
src/libm-tester/iutsimd.c

This patch removes the special case where you need to specify additional source file for the iutadvsimd executable.

[#56] Add consisten compilation of arm simd test executable

---

CMakeLists.txt
Configure.cmake
cmake/Scripts/GenerateRenameHeader.cmake
src/CMakeLists.txt
src/common/CMakeLists.txt
src/libm-tester/CMakeLists.txt
src/libm/CMakeLists.txt

This patch adds the gnuabi compatible version of sleef. It was tested on the downstream CI.
Note: libsleefgnuabi.so is installed alongside libsleef when invoking `make install`

Build libsleefgnuabi.

---

Configure.cmake

I think sleef should have "Release" as the default cmake build type because there is code that require the optimisation flags to be turned on.
I have wrote the code such that if a build type if specified, our default will not overwrite the user's preference.

Default to optimised build to enable full support.

---

Configure.cmake
src/libm/CMakeLists.txt

This is a followup of the discussion in #69 about file dependencies not being tracked properly.
The libm/CMakeLists.txt is quite simplified by this commit and tracks correctly file dependencies between targets, so a rebuild without nothing changed doesn't trigger anything.
Must be merged after #69 an #70

[cmake] Add precise file deps and refactor libm/CMakeList.txt

---

CMakeLists.txt
Configure.cmake
src/libm/CMakeLists.txt

This is a continuation on top of #69, #70 and #72 
Currently, this can be only activated by passing `-DSLEEF_ENABLE_LLVM_BITCODE=1 ` to cmake.
It outputs the LLVM bitcode ll files to lib for now.

[cmake] Add support for generating LLVM bitcode files

---

src/libm-tester/Makefile
src/libm/mkrename_gnuabi.c
src/libm/sleefsimdsp.c

This patch added the missing GNU ABI "finite" names for single precision computation.

[gnuabi] Add finite names for single precision.

---

Configure.cmake
src/libm-tester/CMakeLists.txt
src/libm/CMakeLists.txt

On some Unix systems the libm dependency of libsleef and
libsleefgnuabi needs to be made explicit to avoid runtime failures in
the tests reporting "missing symbol: sqrt".

[cmake] Fix libm dependency

---

.travis.yml
CMakeLists.txt
src/libm-tester/CMakeLists.txt

The old `test-libm` custom target have been replaced by the facilities provided with ctests.

[cmake] Cmake uses ctests

---

include/Makefile
src/libm/Makefile

With this patch, build failure in a parallel build is prevented.
Sometimes build failed in a parallel build since sleef.h is read by another process before it is written completely.
With this patch, sleef.h is once output to sleef.h.0 and then renamed to sleef.h.
If mv command is atomic, build failure should be prevented.

[Makefile] Prevent build failure when build in parallel

---

.travis.yml

This patch runs the build and tests in parallel, with two parallel
runs which are available according to [1].
It also removes the verbose output.
[1] https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments

[travis] Run tests in parallel.

---

Configure.cmake
src/libm-tester/CMakeLists.txt

This patch-set implements fixes for the cmake build system, on aarch64, and also reactivate scalar testing for all architectures.

Various cmake fixes

---

src/arch/helperadvsimd.h

This patch fixes a type mismatch error preventing building for advsimd.
There was a type mismatch error between int64x2 and uint64x2 data types, which crept in without noticing.

[Advsimd] This patch fixes error in advsimd helper.

---

src/libm/sleefdp.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/libm/sleefsp.c

This patch improves computation speed of log.
This patch improves computation speed of log functions by simplifying calculation and adding more opportunity for out-of-order parallelization with CPU's pipeline.
With this patch, the computation speed of xlog_u1 is increased by 16%, which means the ratio between computation time of the previous implementation and the new implementation is 116%.

[Performance] Speed improvement of log

---

src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

This patch replaces the `__extension__ __typeof` keywords used to
define the GNUABI "finite" symbols with a explicit declaration of the
functions.
This is done to prevent two problems:
1. avoid using GCC specific extension like `__extension__ __typeof`
that not all compiler support;
2. make sure that the "finite" symbols have global visibility in the
shared library.

[gnuabi] Avoid GCC extensions for finite names.

---

src/libm/dispavx.c.org
src/libm/dispsse.c.org
src/libm/mkrename.c

Const attribute was missing in sleef.h.
It seems that this patch does not affect the gnuabi version of the functions, but please check.

[Function attributes] This patch adds const attribute to the exported functions.

---

src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helperavx512f.h
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

With this patch, kernels can be splitted into odd and even parts in order to make computation faster.
If the processor is powerful enough, these two parts can be executed in parallel by out-of-order execution.
However, there is some overhead that is required to split the original kernel into two.
The degree of speed-up depends on the micro architecture. It may be slower on some micro architectures.
This feature is enabled by SPLIT_KERNEL macro, and currently, it is enabled only for AVX2 and AVX512F.
This change affects computation speed of many functions, but for example,
the ratio of execution time between the previous version and the new version of asind4_u35 is 2.08.

[Performance] Improving speed by splitting kernels

---

src/libm/CMakeLists.txt
src/libm/Makefile
src/libm/Makefile.vc
src/libm/sleeflibm_footer.h.org
src/libm/sleeflibm_header.h.org

This is a fix for Windows for importing correctly `sleef.lib` and exporting functions using extern "C" so that they are correctly exported in the DLL (without C++ mangling names)
I have updated the way the headers are concatenated with now a `sleeflibm_header.h.org` and `sleeflibm_footer.h.org`

Use sleef.lib on Windows. Export functions with extern "C"

---

.travis.yml

After the merge of https://github.com/shibatch/sleef/pull/112,
`libdft` gets compiled and tested via cmake, so there is no need to
have this Makefile compilation of `libdft`.

[travis] Remove Makefile compilation.

---

CMakeLists.txt
src/common/CMakeLists.txt
src/dft/CMakeLists.txt
src/libm-tester/CMakeLists.txt
src/libm-tester/tester2simddp.c
src/libm-tester/tester2simdsp.c
src/libm/CMakeLists.txt

This patch moves functions defined in src/common/common.c from libdft to libsleef.
https://github.com/shibatch/sleef/issues/120
It also adds dispatchers to libsleef. 
https://github.com/shibatch/sleef/issues/121
It also removes linking with object files and substitute it with linking with static libraries libcommon and libarraymap.

[cmake] Move functions in common.c to libsleef

---

.travis.yml
src/libm-tester/iutsimd.c
src/libm/CMakeLists.txt
src/libm/dispavx.c.org
src/libm/dispsse.c.org
src/libm/funcproto.h
src/libm/mkdisp.c
src/libm/mkrename.c
src/libm/mkrename_gnuabi.c
src/libm/sleeflibm_footer.h.org
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

This patch fixes the problem in which the dispatchers do not choose the best available extension.
https://github.com/shibatch/sleef/issues/133
In order to prevent a similar bug to be made again, the selected extension will be displayed upon execution of iutdsp128 and iutdsp256.

[dispatcher] Fix dispatcher

---

.travis.yml
src/arch/helperadvsimd.h
src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helpersse2.h
src/common/misc.h
src/libm-tester/tester.c
src/libm/dd.h
src/libm/df.h
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

vmaxnum_v*_v*_v* and vminnum_v*_v*_v* are helper functions for utilizing instructions for choosing larger and smaller elements from two given vectors, and they are introduced in the following PR.
https://github.com/shibatch/sleef/pull/109
It is said that vmaxnmq and vminnmq on aarch64 are IEEE754-conformant, but I recently found that handling of signalling NaN by these instructions is not conforming to the specification of fmin and fmax functions in the ANSI C standard.
This patch fixes that problem.

[aarch64] Fix fmin and fmax on aarch64

---

appveyor.yml
src/libm-tester/CMakeLists.txt

This patch fixes a bug in CMakelists.txt which was preventing build static libs with MSVC.
This patch also adds directive for building static libs on appveryor.

[MSVC][CMake] Enable building static libs on MSVC

---

CMakeLists.txt
Configure.cmake
src/arch/helperneon32.h
src/libm-tester/CMakeLists.txt
src/libm-tester/iutsimd.c
src/libm/sleefsimdsp.c

Usage of FMA is enabled on hardware with vfpv4 support.
This patch won't change the existing functions.

[AArch32] This patch adds neon32+vfpv4 target support.

---

CMakeLists.txt

The CMake Policy CMP0066 is not specified in the CMake file which produces some developer warnings (see below). It controls whether CMAKE_C_FLAGS and friends are honored in the `try_compile` tests (that is, whether they are passed to the compiler while building these tests). 
The new recommended behavior is to pass these flags, but for backwards compatibility this behavior is disabled by default. The first version that supports the new behavior is CMake 3.7.2 (AFAICT) which is larger than the minimum supported CMake version. 
This PR sets the behavior to the old one for consistency across all supported CMake versions. Once the minimum updated cmake version is updated to 3.7.2 or newer, this behavior should be changed to the new one by setting this policy to `NEW`. 
---
Example warning: …

Set CMP0066 to the behavior of CMake 3.4.3

---

.travis.yml
CMakeLists.txt
Configure.cmake
Jenkinsfile
src/arch/helperadvsimd.h
src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helperavx512f.h
src/arch/helperpower_128.h
src/arch/helperpurec.h
src/arch/helperpurec_scalar.h
src/arch/helpersse2.h
src/arch/helpersve.h
src/arch/helpervecext.h
src/libm-tester/CMakeLists.txt
src/libm-tester/iutsimd.c
src/libm-tester/tester2simddp.c
src/libm-tester/tester2simdsp.c
src/libm/CMakeLists.txt
src/libm/dd.h
src/libm/df.h
src/libm/sleeflibm_header.h.org
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
travis/before_install.x86_64-clang.sh
travis/before_install.x86_64-gcc.sh

This patch adds pure C scalar helpers with which scalar functions are implemented using the SIMD source code.
It also adds helper files which do not use FMA on platforms with FMA support.

[Determinism] Add purecscalar and noFMA helpers

---

src/libm-tester/iut.c
src/libm-tester/iutsimd.c
src/libm-tester/tester.c
src/libm-tester/testerutil.c
src/libm-tester/testerutil.h
travis/script.aarch64-gcc.sh
travis/script.armhf-gcc.sh
travis/script.osx-clang.sh
travis/script.osx-gcc.sh
travis/script.ppc64el-clang.sh
travis/script.x86_64-clang.sh
travis/script.x86_64-gcc.sh

With this patch, testing time is reduced to 50%.

[Tester] Faster tester and iut

---

.travis.yml
Configure.cmake
Jenkinsfile
src/libm/CMakeLists.txt

This patch includes fix for issue https://github.com/shibatch/sleef/issues/232 and PR https://github.com/shibatch/sleef/pull/231.
It also includes changes of CI setting for removing GCC/OSX testing on travis. This is because updating gcc with brew takes too much time now. Instead of this, build with gcc is now tested on Jenkins.

Change settins for build and CI

---

Jenkinsfile
src/arch/helperavx.h
src/arch/helperpower_128.h
src/arch/helperpurec_scalar.h
src/arch/helpersse2.h
src/arch/helpersve.h
src/quad-tester/qiutsimd.c
src/quad-tester/qtester.c
src/quad-tester/tester2simdqp.c
src/quad/qfuncproto.h
src/quad/sleefquad_header.h.org
src/quad/sleefsimdqp.c

This patch adds Sleef_strtoq and Sleef_qtostr which can be used to convert between a quad value and a string. These functions are not vectorized. The corresponding testers are also added.
This patch also adds functions for subtraction.
Intel compiler testing is temporarily disabled because of license expiration.

[Quad] Add functions for conversion between quad and string

---

src/libm/mkrename.c

These functions are not defined with vectorcc so they shouldn't be declared with it either.
Similar to https://github.com/shibatch/sleef/pull/241. The name change makes this very easy to catch...

Remove vectorcc from getInt and getPtr declarations

---

src/libm/sleefsimddp.c

Found this when trying to use clang to compile sleef on windows with vectorcall calling convention. The calling convention changes the symbol name making this very easy to detect when fixing aliases.

Add missing VECTOR_CC for sincos

---

src/libm/dispavx.c.org
src/libm/dispsse.c.org

Currently a no-op but this makes it easier to support vector call attribute on x86,
which might be necessary on windows.
This is not a bug fix but it should also be harmless. This is likely the last part of the change I had to compile with clang+vectorcall ABI that is mergable. The [rest of the changes](https://github.com/shibatch/sleef/commit/5ccf30a25cbb98c91a2637ad4a12254b76021434) are fairly small (in line number) and much dirtier so it will certainly require cleanup and may or may not be wanted due to GCC compatibility... (since the two ABI uses different symbols, however, it might be possible to ship a binary with both version with the same function names....)

Add (no-op) VECTOR_CC to sse/avx dispatch

---

doc/html/aarch64.xhtml
doc/html/ppc64.xhtml
doc/html/x86.xhtml

This fix the following typo
* Sleef_double_2 -> Sleef_double2
* Sleef_float_2 -> Sleef_float2

Fix typo in html doc

---

src/libm/sleefdp.c
src/libm/sleefsimddp.c

On very rare occasions, the error with tan_u35 exceeds 3.5 ULP.
This patch fixes this problem.

Fix tan_u35

---

src/arch/helperavx.h
src/libm/dispavx.c.org

FMA4 support is in bit 16 of register ECX, not EDX of the "extended
processor info" (0x80000001).
The mapping of registers to reg is:
reg[0] = eax
reg[1] = ebx
reg[2] = ecx <---
reg[3] = edx
Bit 16 of EDX is PAT (Page Attribute Table) on AMD CPUs, which is widely
supported. Intel CPUs do not set this bit. This causes "Illegal instruction"
errors on AMD CPUs that do not support FMA4.
See https://github.com/pytorch/pytorch/issues/12112
See https://github.com/shibatch/sleef/issues/261
http://developer.amd.com/wordpress/media/2012/10/254811.pdf (Page 20)
Fixes #261

Fix FMA4 detection

---

src/common/arraymap.c
src/libm/CMakeLists.txt
src/quad/CMakeLists.txt

The compiler-specific condition for `type` and `cat` is incorrect. Also `<io.h>` is missed for `_get_osfhandle`.

Fix compilation under Windows with MinGW

---

src/arch/helpersve.h

The signed versions of LSR and unsigned versions of ASR are not
defined in SVE ACLE - https://developer.arm.com/docs/100987/latest.

[SVE] Replace use of unsupported SVE ACLE intrinscis.

---

src/common/common.c

Dear Prof. Shibata, 
First of all thank you for providing this library. I am using it with PyTorch on OpenBSD.
With this simple fix your library builds without errors on OpenBSD and all tests pass except for the ilogb denormal/nonnumber tests where "correct" return INT_MIN for inf arg. This appears to be due to a bug in the OpenBSD amd64 implementation of ilogb as the [documentation](https://man.openbsd.org/ilogb) states that the function should return INT_MAX for inf arg. Tests return INT_MAX.
Best regards,
XG6

Build on OpenBSD

---

src/libm/CMakeLists.txt

When SSE2 is disabled (or not supported by compiler), dispsse_obj target compilation fails. This fixes this issue by disabling its build when SSE2 is not present.

Disables compilation of dispsse_obj target when SSE2 is disabled

---

src/libm/CMakeLists.txt

When AVX is disabled (or not supported by compiler), dispavx_obj target compilation fails. This fixes this issue by disabling its build when AVX is not present.

Disables compilation of dispavx_obj target when AVX is disabled

---

Configure.cmake

In Configure.cmake, there are typos in definition for ENFORCE_AVX (lines 445 and 446). 
This fixes those.

Fixes ENFORCE_AVX option

---

src/arch/helperavx512f.h

This patch allows rounding operations to use _mm512_roundscale_pd or _mm512_roundscale_ps with AVX-512. This should make the whole computation faster.
This PR addresses issue https://github.com/shibatch/sleef/issues/285.

[AVX-512] Use roundscale for rounding

---

.travis.yml
Configure.cmake
src/arch/helperpower_128.h
src/libm-tester/iutsimd.c
src/libm-tester/tester2simddp.c
src/libm-tester/tester2simdsp.c
src/libm-tester/tester3.c
travis/before_install.common.sh
travis/before_script.common.sh
travis/script.common.sh

- fix the build on gcc
- fix accuracy tests
- fix the build with C++ when 'vector' compiler token is combined,
NOTE: the generated header is using '__vector' instead of 'vector'
- fix unaligned memory load
- set rounding to the nearest even, make it equivalent to X86
- improve the performance of conversions
- improve the performance of shuffles and reverses
- cleanup the whole VSX implementation

PPC64LE: Fix build issue on gcc

---

src/libm/sleefdp.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

This patch simplifies rint algorithm that are used when such an instruction is not available.
This patch also replaces sqrt algorithm with FMA.
These changes do not affect performance with recent vector extensions.

Simplify rint

---

CMakeLists.txt
appveyor.yml
src/libm-tester/CMakeLists.txt
src/libm-tester/tester.c
src/quad-tester/qtester.c

With this patch, testing will fail if IUT crashes.
This patch also adds ENFORCE_TESTER cmake option which make a build fail if no tester is available.

Better error detection

---

appveyor.yml
include/sleefdft.h

This patch adds extern "C" declaration to sleefdft.h, as suggested in issue https://github.com/shibatch/sleef/issues/298.

Add extern C declaration to sleefdft h

---

src/libm-tester/testerutil.h

This patch fixes a small bug in testerutil.h.
This bug makes builds with gcc-10 fail.

Add "extern" to the reference to enableFlushToZero in testerutil.h

---

CMakeLists.txt
Configure.cmake

Search for the static libraries instead and add -static to CFLAGS

Build static bins if BUILD_SHARED_LIBS is defined

---

src/common/common.c
src/common/f128util.h
src/common/misc.h
src/libm-tester/tester.c
src/libm-tester/tester3.c
src/libm-tester/testerutil.c
src/libm-tester/testerutil.h
src/libm/sleefdp.c
src/libm/sleefqp.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/libm/sleefsp.c
src/quad-tester/qtesterutil.c
src/quad/sleefsimdqp.c

This patch changes suffixes of constants to a more portable form.
For example, 1LL is changed to INT64_C(1).

Change suffixes of constants

---

src/libm/sleeflibm_header.h.org
src/quad-tester/CMakeLists.txt
src/quad-tester/qtesterutil.c

This is caused because __float128 is defined since gcc-8, and even though it does not define `__SIZEOF_FLOAT128__`.

Fix build problem with gcc-10 on ppc64

---

src/common/misc.h
src/libm/sleeflibm_header.h.org
src/quad-tester/CMakeLists.txt
src/quad-tester/qiutsimd.c
src/quad-tester/qtester.c
src/quad-tester/qtesterutil.c
src/quad-tester/tester2simdqp.c
src/quad-tester/tester3printf.c
src/quad/CMakeLists.txt
src/quad/qfuncproto.h
src/quad/sleefsimdqp.c

This patch adds functions for casting between 64-bit integer and quad.
It also fixes a bug in quad-precision log1p function.

[Quad] Add quad cast functions

---

src/libm/sleefsimddp.c

C standard do not define have left shift should affect the sign bit, which results in the following runtime error if `vilogbk_vi_vd` is compiled by clang with sanitizer checks enabled:
```
sleef/src/libm/sleefsimddp.c:329:49: runtime error: left shift of 4095 by 20 places cannot be represented in type 'int'
```
Can be fixed by explicitly specifying type of shift 1st operand as unsigned: i.e. replacing `1` with `1U`

Fix undefined behaviour in vilogbk_vi_vd

---

src/libm/sleefsimdsp.c

C standard does not define how sign bit should be handled during left shift, which triggers UBSAN runtime error:
```
src/libm/sleefsimdsp.c:3031:101: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
```
Discovered while working on https://github.com/pytorch/pytorch/pull/48275

Fix undefined behavior in `xnextafterf`

---

src/libm-benchmarks/Makefile
src/libm-benchmarks/benchsleef.c
src/libm-benchmarks/benchsleef128.c

This patch adds s390x and ppc64le support to the benchmarking utility.

Add s390x and ppc64le support to the benchmarking utility

---

src/arch/helperadvsimd.h
src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helperavx512f.h
src/arch/helperpower_128.h
src/arch/helperpurec_scalar.h
src/arch/helpers390x_128.h
src/arch/helpersse2.h
src/arch/helpersve.h
src/common/commonfuncs.h
src/common/keywords.txt
src/common/keywords_cuda.txt
src/libm/sleefsimddp.c
src/quad/sleefsimdqp.c

This is another patch for cleanup.
It introduces two helper functions vcast_vm_i64 and vcast_vm_u64 which substitute vcast_vm_i_i if appropriate.

Use vcast_vm_i64 and vcast_vm_u64 instead of vcast_vm_i_i

---

src/dft/CMakeLists.txt
src/libm/CMakeLists.txt
src/quad/CMakeLists.txt

> A DESTINATION without a block will provide a default for all blocks,
> because DESTINATION is always required prior to CMake 3.14, even if it's
> already provided in a previous install rule and install rules for
> targets had to be split in two prior to CMake 3.12.
Fixes: #417

Provide dummy destination in namelink install

---

.github/workflows/build_and_test.yml
Configure.cmake
src/libm-tester/CMakeLists.txt
travis/toolchain-ppc64el.cmake

As discussed offline, this PR adds some CI on GitHub Actions. That's expected to facilitate contribution by having smoke testing on any changes that would be integrating, facilitating the work of maintainers by making sure a change will not completely break all supported architectures (aarch64, arm, ppc64, s390x, and x86_64).

Add CI on Github Actions for x86_64, aarch64, arm, ppc64 and s390x

---

src/libm-tester/testerutil.c
src/libm-tester/testerutil.h

These two functions were added to the MPFR API.
Fixes #458.
This is offered as alternative to https://github.com/shibatch/sleef/pull/462, in case you would like to maintain backwards compatibility with MPFR versions earlier than 4.2.0. I don’t view either PR as better than the other; it’s merely a matter of choice.

Do not define our own mpfr_sinpi/mpfr_cospi for mpfr 4.2.0 and later

---

src/libm-tester/testerutil.h

Missed of the previous patch - this may already be provided by math.h.

Remove warning about M_PIf redefinition

---

Configure.cmake
src/libm-tester/tester3.c

Removes warnings about deprecation of old API for versions of OpenSSL above 3.0.
Needed to amend openssl link line to avoid a crash in tester3 with old openssl.
Fixes #486.

Switch from old to new MD5 API in tester3.

---

.github/workflows/build_and_test.yml

PR #477 pointed out some test failures with qemu.
However, following the discussion on this PR cannot see exactly what these failures were (none of the GHA past builds show runs for these settings). Locally, cross compiling aarch64 on x86 host with llvm-17 and using user-mode qemu emulation environment do not
show failures.
Therefore we try to enable these tests in GHA and check for failures.
Note: This issue is being tracked in #485

Enable aarch64 llvm-17 cross compilation tests

---

src/libm-tester/CMakeLists.txt

This test suite covers the usage of scalar symbols with auto-vectorisation, to test the GNU ABI
symbols generated by SLEEF.
However, some failures are recorded when emulating these tests using user mode QEMU, for a
cross-compile build for AArch64 and s390x.
This is because this test suite does not get called with the EMULATOR command necessary.
This fix adds the emulator to the test command
which makes the tests pass when cross-compiling
and using user mode QEMU emulation.

Add qemu command prefix to testervecabi tests

---

Configure.cmake

Macs do not implement SVE yet and Darwin does not support it.
Should solve #425 and #487.

Disable SVE on MacOS/Darwin

---

src/arch/helperrvv.h

Make the vmask types for single-precision and double-precision interfaces compatible, so that we have fewer divergent functions.
Keep the vopmask types incompatible, because the underlying vbool*_t types still encode some underlying assumptions about the number of lanes involved.
Make the still-incompatible function names distinct between SP and DP, and then reconcile these with the preprocessor at the end of the file so that the caller still sees the expected operations.  This will help when it comes to generating inline headers in a future revision.

Reconcile RVV mask types.

---

src/arch/helperrvv.h

Prefer use of __riscv_vcreate_*() intrinsics, where appropriate.  This
does away with piecemeal assembly of a tuple register types and ensures
that every component is defined.  It also gets rid of uninitialised
variable warnings.
__riscv_vcreate intrinsics aren't available in older toolchains but will
be available in version 1.0 of the intrinsics interface.  In the interim
include substitute macros which try to fill the gap as best as possible.
Use a regular pattern of cast-then-insert, and extract-then-cast when
dealing with tuple registers with mixed component types.
Remove a few unused macros, etc..

Clean up RVV register composition.

---

src/libm/CMakeLists.txt

Fix "SLEEF_BUILD_SCALAR_LIB" lost function to control build sleefscalar lib.
|Status|Control Build|Control Install|
|----|----|----|
|Current Code| No |Yes|
|This PR|Yes|Yes
Original code: `SLEEF_BUILD_SCALAR_LIB` only control whether install scalar_lib, it would always build scalar_lib.
My PR: `SLEEF_BUILD_SCALAR_LIB` control both whether build and install scalar_lib.

Fix SLEEF_BUILD_SCALAR_LIB lost function

---

src/arch/helperrvv.h

Depends on #520, and #521, #503, and #522.
The first commit is already in the #521 PR, but repeated here so I don't have to rebase #503 and #522.
The relevant changes are: https://github.com/rivosinc/sleef/commit/78ea02c2ab1df54d929a92fcaf5935e06c714563

add comments to helperrvv.h

---

src/arch/helperrvv.h

__riscv_vcreate* appear after RVV intrinsics v0.12, and the next version after that is v1.0 which is not yet ratified.
Nevertheless, clang-18 and up already have the support we need.

Fix RVV intrinsic version detection.

---

src/libm/sleefdp.c
src/libm/sleefinline_header.h.org
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/libm/sleefsp.c
src/quad/sleefquadinline_cuda_header.h.org
src/quad/sleefquadinline_header.h.org
src/quad/sleefsimdqp.c

Warning message on MSVC:
```cmd
28>D:\xu_github\sleef\src\libm\sleefsimddp.c(28,9): warning C4068: unknown pragma 'STDC'
28>sleefsimdsp.c
28>D:\xu_github\sleef\src\libm\sleefsimdsp.c(28,9): warning C4068: unknown pragma 'STDC'
28>Generating Code...
```
Fix it by conditional defination for disable fp contractions.

Fix disable fp contractions warning on msvc

---

src/gencoef/gencoef.c
src/libm-tester/tester.c
src/libm-tester/tester2dp.c
src/libm-tester/tester2simddp.c
src/libm-tester/tester2simdsp.c
src/libm-tester/tester2sp.c
src/quad-tester/qtester.c
src/quad/sleefsimdqp.c

This fixes some of the messages coming up in asan test output, but not all of them. Same number of test suites failing after this change.

Add matching mpfr_clear statements for mpfr_init

---

src/libm/CMakeLists.txt
src/libm/disps390x_128.c.org
src/libm/tryvxe2.c

Change the detection mechanism for the VXE2 feature from signal handling to getauxval. This is a bit simpler and also helps in multi-threaded uses of the library as in PyTorch:
https://github.com/pytorch/pytorch/issues/128503
In particular it prevents the sigjmp file scope variable from being accessed from multiple threads. This used to cause crashes with the way PyTorch uses Sleef in combination with OpenMP. In that case cpuSupportsExt is executed simultaneously by multiple threads what led to parallel writers to sigjmp. This used to be no problem running on IBM z15 and newer, where there is actually VXE2 available. However, running on IBM z14 the signal handler gets executed what actually makes use of the corrupted sigjmp data structure to get back into cpuSupportsExt.

S/390: Use getauxval for detecting VXE2 to fix #560

---

docs/2-references/libm/README.md

The acosh function is only defined for values greater or equal to 1. Documentation was updated according to this.
Fixes #569

Update acosh documentation

---

.github/workflows/check_compatibility.yml

Add a new workflow to detect unexpected backward-incompatible changes at precommit, by comparing current version against a reference version, both generated on Linux with gcc. It uses abidiff to compare ELF-format shared libraries. This is the tool used by Fedora to report a recent breach in API #534. Test should fail until it is fixed by #545.

Add checks for incompatible changes in GHA

---

src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helperavx512f.h
src/arch/helperneon32.h
src/arch/helpersse2.h

* This update is required to build the library with newer compilers, especially MSVC.
* Notation like ((vdouble) { +0.0, -0.0, +0.0, -0.0 }) is not compliant to the standards, and had to be replaced with vector-set intrinsics.
* Added explicit typecasting so that the code can be compiled with C++ which has strict type checking.
This is part of the patches that implements https://github.com/shibatch/sleef/issues/574.
This is manually rebased https://github.com/shibatch/sleef/pull/586.

Update the helper files so that the library can be compiled with newer compilers

---

src/arch/helperpower_128.h
src/arch/helperpurec_scalar.h
src/arch/helpers390x_128.h

It adds explicit typecasting so that C++ compilers can compile the inline headers generated from these helpers.
* This patch addresses the problem where the inline headers for ppc64el, s390x and purec_scalar cannot be compiled with C++ compilers.
This patch updates helpers for ppc64el, s390x and purec_scalar.
It adds explicit typecasting so that C++ compilers can compile the inline headers generated from these helpers.
This is part of the patches that implements https://github.com/shibatch/sleef/issues/574.

This patch updates helpers for ppc64el, s390x and purec_scalar.

---

CMakeLists.txt
docs/1-user-guide/build-with-cmake/README.md
docs/4-tools/README.md
src/CMakeLists.txt
src/benchmarks/CMakeLists.txt
src/benchmarks/README.md
src/benchmarks/benchmark_callers.hpp
src/benchmarks/benchmark_templates.hpp
src/benchmarks/benchsleef.cpp
src/benchmarks/gen_input.hpp
src/benchmarks/type_defs.hpp

* Improve code quality 
Added new benchmark tool to SLEEF project using googlebench framework.
In theory this tool can benchmark any unary and binary function in SLEEF.
Benchmark is enabled in all functions listed in benchsleef.cpp. This list uses macros in benchmark_callers.cpp, so that we can enable benchmarking in multiple precisions using single lines of code. It is also possible to list the exact function we want, as each of the macros in benchmark_callers.cpp can be called independently and connected like building blocks.
The tool is integrated with SLEEF via CMake, meaning it can be built automatically when SLEEF is built. To enable that, pass CMake argument -DSLEEF_BUILD_BENCH=ON.
This tool depends on C++17 standard.
Tested on aarch64 for scalar, vector and …

Integrate Google benchmarks into SLEEF

---

src/libm-tester/tester.c
src/libm/sleefsimdsp.c

* Fix bugs
* On aarch32, cbrt(4) was returned instead of M_PI/2 when INFINITY is given to atanf.
* Due to a bug in gcc-13, sign of tanf(+-0) was wrong with PUREC_SCALAR.
* Changed a constant in sleefsimdsp.c to fix the value returned by xatanf when INFINITY is given on aarch32.
* Add a workaround that fixes the wrong sign of tanf with PUREC_SCALAR when compiled with gcc-13.
* Add testing for the first problem. The second problem is detected by the existing tester.
These changes are required to implement https://github.com/shibatch/sleef/issues/574, because these problems are also detected by the new tester.

This patch fixes two problems

---

src/common/addSuffix.c
src/gencoef/gencoef.c
src/gencoef/simplexfr.c
src/libm/sleefsp.c
src/quad/sleefsimdqp.c

* Improve code quality
This PR consists in fixing a few errors reported by cppcheck (UB, memleak, and other vulnerability)

Fix errors reported by cppcheck 

---

.github/workflows/build-as-subproject.yml
.github/workflows/build-examples.yml
.github/workflows/build_and_test.yml

* Modify a job in an existing workflow
This PR consists in updating gh-runners in linux native and cross build/test workflow, to use ubuntu-24.04 instead of ubuntu-latest. The main reasons are
- It is clearer to use explicit version of Ubuntu.
- update of ubuntu-latest to 24.04 is on hold because it disturbs a lot of workflows out there. But it is useful to use and does not create issues. https://github.com/actions/runner-images/issues/10636
PR also removes some expensive tests for RISC-V.
This will ultimately unlock the use of latest versions of gcc 12, then gcc 13, and finally gcc 14.
Gcc 14 itself will unlock more testing.
So it could relate to #439, and enable #539, ...
This PR does not update the version of gcc yet, just to make sure old version still pass tests.

Update GH runners to Ubuntu 24.04

---

Configure.cmake

To test for RVV1 support, we currently run a small program that uses some vector intrinsics from the v0.11.x draft of the RVV standard. The library itself however needs newer intrinsics than the ones that we test for. This can lead to a problem because GCC 13 supports the intrinsics that we test for, but not (all of) the ones we intend to use. In short, the build can fail with GCC 13: https://github.com/shibatch/sleef/issues/579
This commit changes the detection mechanism. Instead of compiling a program that makes use of the intrinsics, we now just check the two values, `__riscv_v` and `__riscv_v_intrinsic`, to ensure that we have version 1.0 of RVV and version 0.12 of the intrinsics. According to the intrinsics spec, https://github.com/riscv-non-isa/rvv-intrinsic-doc, these are the …

Configure.cmake: improve RVV1 check

---

README.md

Both links are the ony locations, where a xhtml document was referenced 
-- 
Regards ... Detlef

README.md: Fix broken *.xhtml links

---

src/common/misc.h
src/libm-tester/tester.c
src/libm/sleefdp.c
src/libm/sleefsimddp.c

* Fix a bug and add tests
This PR consists in updating overflow threshold used in exp and pow.
Fixes #523.
Relates to #600.

Fix oflow bound in exp and pow.

---

src/common/misc.h
src/libm-tester/tester.c
src/libm/sleefdp.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/libm/sleefsp.c

* Fix a bug and add test to catch such issue in the future
This PR consists in fix overflow behaviour in log1p(f) scalar and SIMD.
Fixes #473
Relates to #600 (where it is also reported)
Please on focus on method chosen to fix approximation between old oflow threshold and max float/double.
Interval was thoroughly tested for log1pf and log1p, but testing is always as good as it gets to double precision.

Update overflow bound in log1p(f)

---

CMakeLists.txt
Configure.cmake

* Improve code quality or performance
Add a switch to turn off involve `libm`. It will bring duplicate math function on Windows.
1. `libm` is special library, it is usually appeared on Linux, but we not use it on Windows.
2. On Windows, Microsoft provided math functions on its runtime libraries, such as ucrt.lib.
3. In some case, such as Intel compiler environment, Intel provided a `libm` for high performance purpose. `Sleef`'s `find_library(libm m)` will involve the `libm` into project. So, we would occur the symbol conflict issue on math functions.
My solution is add a switch(option) to let upper CMake project turn off `libm` involvement. It default value is on, and keep compatible to original logical.
Relates to/Fixes [([Intel GPU] Symbol conflict between libm.lib and ucrt.lib for …

[CMake] add a switch for libm.

---

CMakeLists.txt
docs/4-tools/README.md
src/libm-benchmarks/CMakeLists.txt
src/libm-benchmarks/README.md
src/libm-benchmarks/benchlibm.cpp
src/libm-benchmarks/benchmark_callers_libm.hpp
src/libm-benchmarks/benchmark_templates.hpp
src/libm-benchmarks/gen_input.hpp
src/libm-benchmarks/type_defs.hpp

* Improve benchmark tool
Extended current benchmark tool with support to benchmark of libm functions. Libm benchmark is enabled in all functions listed in benchlibm.cpp.
It interfaces with the rest of the existing tool through benchmark_callers_libm.hpp (defines macros which simplify how the list of functions to benchmark looks like as it groups functions by precision/accuracy/variant).
The tool is integrated with SLEEF via CMake, meaning it can be built automatically when SLEEF is built. To enable that, pass CMake argument -DSLEEF_BUILD_BENCH=ON and
-DSLEEF_BUILD_BENCH_REF=ON.
Note this option is only enabled on Linux OS.
Subject to internal review

Add libm benchmarks

---

src/libm-benchmarks/plot-tool/plot_results.py
src/libm-benchmarks/plot-tool/plotter.py
src/libm-benchmarks/plot-tool/preprocessing.py
src/libm-benchmarks/plot-tool/preprocessing_validators.py
src/libm-benchmarks/plot-tool/requirements.txt

* Add internal tool to plot graphs with benchmark results.
Add a tool capable of processing and plotting the results produced by the new benchmark tool. Also support comparison with reference (assumes libm).
Produces 1 graph per (precision, accuracy, arch, compiler) showing performance for various variants (scalar, vector and scalable vector).
Relates to Issue #9.

Add plotting tool

---

src/arch/helperpower_128.h

Fixes #611.
* Fix a bug
On GCC 15 and later, fall back to inline assembly instead of using removed intrinsics `__builtin_vsx_xvcvsxwdp()` and `__builtin_vsx_xvcvdpsxws()`.
This PR works around the removal of PowerPC intrinsics `__builtin_vsx_xvcvsxwdp()` and `__builtin_vsx_xvcvdpsxws()` in GCC 15.
Relates to/Fixes #611 
Consider whether it would be better to replace `__builtin_vsx_xvcvsxwdp()` with `vec_doublee`/`vec_doubleo` as suggested in https://github.com/gcc-mirror/gcc/commit/fd9fdb33ae252ec34cc33675433eb56637905257, and to replace `__builtin_vsx_xvcvdpsxws()` with `vec_signede`/`vec_signedo` as suggested in https://github.com/gcc-mirror/gcc/commit/224cc560a6ac19c9454038efe6230096b46f4806. As noted in https://github.com/shibatch/sleef/issues/611, I’m not prepared to contribute that …

Work around removal of some PowerPC intrinsics in GCC 15

---

src/libm/sleefsimddp.c

This commit fixes a bug in the xexpfrexp function: before calling vsel_vi_vo_vi_vi(), the xexpfrexp function did not use vcast_vo32_vo64() to convert vopmask64 to vopmask32. This omission caused incorrect results in the AdvSIMD implementation of xexpfrexp, making it unable to correctly handle input vectors that contain NaN and 0.0.

fix  xexpfrexp

---

Configure.cmake
src/common/quaddef.h
src/libm/sleeflibm_header.h.org.in

Port Sleef to AIX

---

Configure.cmake
src/dft/CMakeLists.txt

Used in pytorch mobile build. See instructions at https://github.com/qnx-ports/build-files/tree/pytorch_qnx_main .
It doesn't seem like I can get the tester executables to build for cross comp (because libmpfr does not come with QNX) so I did not test the built library (apart from verifying pytorch itself).

Add QNX SDP 8.0, 7.1 Support

---

include/sleefdft.h
src/dft-tester/CMakeLists.txt
src/dft-tester/bench1d.cpp
src/dft-tester/test_dftplanner.cpp
src/dft/dft.cpp
src/dft/dftcommon.cpp
src/dft/dftcommon.hpp
src/dft/flockcompat.h

This PR adds DFT planner testing.

Add DFT planner testing.
