src/arch/helperadvsimd.h
src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helperavx512f.h
src/arch/helperpurec.h
src/arch/helpersse2.h
src/arch/helpervecext.h
src/libm/dd.h
src/libm/sleefdp.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/libm/sleefsp.c

This patch is tested to work with AARCH32.

[fmod] Improve fmod

---

.travis.yml
README.md

Is this a real falure of SLEEF or a CI configuration poblem?
https://travis-ci.org/shibatch/sleef/jobs/285218079

[revert] This is just a test for CI.

---

src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

This is a set of patches coming from master.

Merge current master and the finite symbols patch into cmake-transition.

---

src/dft/Makefile
src/libm/Makefile

The previous patch was not enough and there were still build failures.
This patch should prevent them, though there is still very small posssibility of build failure.

[Makefile] This patch prevents build failure when built in parallel.

---

CONTRIBUTORS.md

@shibatch @jlovejoy @diaena @xoofx @blu : please let me know by Monday (AOE) if the information provided in this list if correct.
If I don't hear from you by then, I'll assume you are happy with the list.

[docs] Add contributors file.

---

.travis.yml

This is me experimenting with travis configuration to see if I can compile AVX512F at least in the linux environment.

[travis] Enable gcc-7 and clang-5.0 on linux.

---

.travis.yml
Configure.cmake
src/arch/helperavx512f.h

This patch should fix misdetection of AVX512F availability happening mainly on macOS.

[AVX512F] Fix misdetection of AVX512F

---

src/arch/helperavx512f.h
src/dft/CMakeLists.txt
src/dft/dft.c

This patch fixes the problem in which the DFT tester does not stop on a computer with AVX512.

[DFT] [AVX512] Fix dft test failure on avx512

---

src/common/common.c

This implements the change suggested by Naoki in [1] to fix the
failure in [2].
[1] https://github.com/shibatch/sleef/pull/157
[2] https://travis-ci.org/shibatch/sleef/builds/334713491

[OSX] Fix OSX testing on Travis CI.

---

src/libm-tester/CMakeLists.txt
src/libm-tester/gnuabi_compatibility.c
src/libm/mkmasked_gnuabi.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

A cmake function for compatibility tests is implemented.

[gnuabi] Add compatibility tests for the masked symbols.

---

CMakeLists.txt
Configure.cmake
src/libm/CMakeLists.txt
src/libm/mkalias.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

[Alias] Add aliases without vector extension name (4)

---

CMakeLists.txt

This patch changes the version number from 3.1 to 3.2

Change version number

---

doc/html/aarch32.xhtml
doc/html/aarch64.xhtml
doc/html/additional.xhtml
doc/html/benchmark.xhtml
doc/html/compile.xhtml
doc/html/dft.xhtml
doc/html/index.xhtml
doc/html/misc.xhtml
doc/html/purec.xhtml
doc/html/x86.xhtml

This patch updates the HTML doc.
After this PR is approved, I am planning to release 3.2.

Update HTML doc (4)

---

.travis.yml
Configure.cmake
Jenkinsfile

This patch adds CMake options for disabling and enforcing detected features.
@gnzlbg Please check if this patch implements all what you want.
https://github.com/shibatch/sleef/issues/206

Add options to disable and enforce features

---

src/libm-tester/tester.c

I found a bug of tester in denormal/nonnumber handling of functions with two arguments.
This patch fixes that bug.
There is no change in the library itself.

Fix tester

---

src/libm/sleefdp.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/libm/sleefsp.c

This patch will update the algorithm for fmod to the version written in the paper.

Update fmod algorithm

---

src/gencoef/mkrempitab.c

This patch adds a program for generating rempitab.c.

Add mkrempitab.c

---

src/arch/helperavx.h
src/arch/helperavx2.h
src/arch/helperavx2_128.h
src/arch/helperavx512f.h
src/arch/helpersse2.h

This patch fixes the build problem with Debug mode.

Fix build problem with debug mode

---

src/libm-tester/tester.c
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c

This patch fixes a bug in remainder function.

Fix remainder

---

src/quad-tester/qiutsimd.c
src/quad-tester/qtester.c
src/quad-tester/tester2simdqp.c
src/quad/qfuncproto.h
src/quad/sleefsimdqp.c

This patch adds xcmpq functions which were missing.

[Quad] Add xcmpq functions

---

src/libm/sleefsimdsp.c

Do not shift into sign bit of int.

Fix undefined behaviour in xnextafterf

---

.travis.yml
Jenkinsfile
src/arch/helperadvsimd.h

This patch fixes the problem pointed out in issue https://github.com/shibatch/sleef/issues/354.

Address issue #354

---

src/arch/helperadvsimd.h

This pull request is made following issue https://github.com/shibatch/sleef/issues/371.

[AArch64] Fix vfma_pn functions

---

Jenkinsfile

This patch adds build-only testing to the Jenkins configuration.

[Arm Mac] Add Arm Mac build-only testing

---

src/common/keywords.txt
src/quad-tester/qiutcuda.cu
src/quad-tester/qiutsimd.c
src/quad-tester/qtester.c
src/quad-tester/tester2simdqp.c
src/quad/qfuncproto.h
src/quad/qmkrename.c
src/quad/sleefsimdqp.c

This patch adds quad-precision frexp and modf.

[Quad] Add frexp and modf

---

README.md
src/libm/dispavx.c.org
src/libm/disppower_128.c.org
src/libm/disps390x_128.c.org
src/libm/dispsse.c.org
src/quad-tester/CMakeLists.txt
src/quad-tester/qiutsimd.c
src/quad/CMakeLists.txt
src/quad/qdispscalar.c.org
src/quad/qmkdisp.c
src/quad/qmkrename.c

This patch adds a dispatcher for the scalar functions in the quad library.

[Quad] Add scalar dispatcher

---

src/libm-tester/CMakeLists.txt
src/libm-tester/iutsimd.c
src/libm/CMakeLists.txt
src/libm/dispscalar.c.org
src/quad/qdispx2.c.org
src/quad/sleefquad_header.h.org

This patch adds a dispatcher to the main library.

Add scalar dispatcher

---

src/libm/dispscalar.c.org
src/libm/tryvsx3.c
src/libm/tryvxe2.c
src/quad/qdispscalar.c.org
src/quad/qdispx2.c.org

This is a follow up from [PR#454](https://github.com/shibatch/sleef/pull/454)

Rename some global variables to avoid clashes

---

CMakeLists.txt
Configure.cmake

Enable/disable address sanitizer with CMake

---

src/arch/helperadvsimd.h
src/arch/helperpurec_scalar.h
src/arch/helperrvv.h
src/arch/helpersve.h
src/common/commonfuncs.h
src/common/dd.h
src/common/df.h
src/common/misc.h
src/libm-tester/iutsimd.c
src/libm-tester/tester2simddp.c
src/libm-tester/tester2simdsp.c
src/libm-tester/tester3.c
src/libm-tester/testerutil.c
src/libm-tester/testerutil.h
src/libm/dispscalar.c.org
src/libm/sleeflibm_header.h.org.in
src/libm/sleefsimddp.c
src/libm/sleefsimdsp.c
src/quad/qdispscalar.c.org
src/quad/qdispx2.c.org
src/quad/sleefsimdqp.c

Add missing headers when needed.

Update copyright years.

---

docs/4-tools/README.md

Restructured some of the sentences in microbenchmark tool section and added commands to install dependencies for sleef's internal microbenchmark tool.

Update microbenchmark tool docs

---

src/quad-tester/tester3printf.c

Propagate change from #489 to quad-tester.
* Remove warning/Avoid future deprecation
Propagate change from #489 to quad-tester.
Relates to #489
Reviewed internally.

Switch from old to new MD5 API in tester3 (quad).

---

.github/workflows/build-as-subproject.yml
.github/workflows/build-examples.yml
.github/workflows/build_and_test.yml
README.md
toolchains/aarch64-gcc.cmake
toolchains/armhf-gcc.cmake
toolchains/native-gcc.cmake
toolchains/ppc64el-gcc.cmake
toolchains/s390x-gcc.cmake

Just checking that it is working.
* Add a workflow to GitHub Actions or add/modify a job in an existing workflow
This PR consists in upgrading to gcc 14 in GHA for Linux and enabling more tests. Making sure all tests pass
May fix issue #573
Relates to issue #481 
Supersedes #539

Update gcc version from 13 to 14 in GHA.

---

.github/workflows/build-and-test-macos.yml
.github/workflows/build-and-test-msys2.yml
.github/workflows/build-as-subproject.yml
.github/workflows/build-cross-llvm-mingw.yml
.github/workflows/build-examples.yml
.github/workflows/build_and_test.yml
.github/workflows/check_compatibility.yml

* modify a job in an existing workflow
This PR consists in upgrading a deprecated action.

Upgrade artifact actions

---

README.md
docs/_config.yml

This PR consists in updating copyright year in documentation.

Udpate copyright year in documentation.

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

This patch adds issue template.

Add issue template

---

Jenkinsfile

This patch adds riscv setting to Jenkinsfile

Add riscv settings

---

README.adoc
src/dft/CMakeLists.txt
src/dft/dft.cpp
src/dft/dftcommon.cpp
src/dft/dftcommon.hpp
src/dft/mkdispatch.c

Modernizing DFT code little by little

Some more modernization of DFT code

---

src/dft/dft.cpp
src/dft/dftcommon.cpp
src/dft/dftcommon.hpp

This patch further modernizes the code for DFT

More cleanup of dft

---

src/dft-tester/CMakeLists.txt
src/dft-tester/dftbench.cpp
src/dft-tester/test_dftplanner.cpp
src/dft/dft.cpp
src/dft/dftcommon.hpp

This patch adds support for 2D DFT benchmarking while fixing small bugs

Add 2D DFT benchmark tool

---

Jenkinsfile

This patch adds LTO testing to Jenkinsfile

Add LTO testing

---

README.adoc

This PR adds the link to the YouTube video of our CoC to the README

Add link to the introduction video of CoC to README
